name = "lbc-blog-tts-api"
main = "index.js"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

account_id = "0ae9944f1896b22fa1aa89acbed7b86b"
workers_dev = true

[vars]
GOOGLE_PROJECT_ID = "913649475121"
GOOGLE_DRIVE_FOLDER_ID = "1BBY-9sfGExHSLv_R2Y8Uznk5OMKhNDfl"

[[env.production.secrets]]
name = "GOOGLE_SERVICE_ACCOUNT_JSON"

[observability]
enabled = true